### ISSUE TITLE
Improve repository appearance

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/reprozip-examples#10]
We could either add some screenshots to the READMEs here or consider making proper HTML pages for the examples. That would allow us to have a gallery-style overview and more styling options for the write-ups.

**Comment by VickySteeves** [comment]
I agree. I use reveal.js for my teaching presentations and it's been really
great. I'm not sure if there are other libraries people typically use for
HTML slides we should look into?

**Comment by remram44** [comment]
Fixed by @VickySteeves with #11
