### ISSUE TITLE
Add opencv tracking example

### ISSUE THREAD

**Issue by fchirigati** [ViDA-NYU/reprozip-examples#22]
Available [here](https://github.com/BinalModi/Computer-Vision-Projects/tree/master/MultipleObjectTracking).

**Comment by remram44** [comment]
We should check ASAP on the bug Binal reported, with the input file to `VideoCapture` not being captured.

**Comment by remram44** [comment]
I cannot reproduce the problem, the input to `cv2.VideoCapture()` correctly shows up in the trace for me.
