### ISSUE TITLE
Instructions for GUI are outdated

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/reprozip-examples#25]
There are multiple ways to proceed:
* Use `--enable-x11`, which requires an X server on the host, and forwards. Works with Docker.
* Use reprounzip-vagrant's `--use-gui`. Faster, doesn't need X server on the host.

**Comment by fchirigati** [comment]
We do mention the first one, right? E.g. [BusVis](https://github.com/ViDA-NYU/reprozip-examples/tree/master/bus-vis#how-to-reproduce). We just need to add the second option as well.

The other instructions that we have is for using the demo VM to pack the GUI application, which is different.

**Comment by remram44** [comment]
Fixed by 67b652c6.
